### ISSUE TITLE
Unable to start guillotina==1.5.2 with default configuration:asyncpg.exceptions.InvalidAuthorizationSpecificationError: role "guillotina" does not exist

### ISSUE THREAD

**Issue by zopyx** [plone/guillotina#141]
```
  File "/Users/ajung/src/guillotina/lib/python3.6/site-packages/guillotina/commands/__init__.py", line 118, in make_app
    return make_app(settings=settings, loop=self.get_loop())
  File "/Users/ajung/src/guillotina/lib/python3.6/site-packages/guillotina/factory/app.py", line 212, in make_app
    loop.run_until_complete(future)
  File "/opt/buildout.python/parts/opt/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/Users/ajung/src/guillotina/lib/python3.6/site-packages/guillotina/db/factory.py", line 56, in PGDatabaseConfigurationFactory
    return await _PGConfigurationFactory(key, dbconfig, app)
  File "/Users/ajung/src/guillotina/lib/python3.6/site-packages/guillotina/db/factory.py", line 44, in _PGConfigurationFactory
    await aps.initialize(loop=app.loop, **connection_options)
  File "/Users/ajung/src/guillotina/lib/python3.6/site-packages/guillotina/db/storages/pg.py", line 428, in initialize
    **kw)
  File "/Users/ajung/src/guillotina/lib/python3.6/site-packages/asyncpg/pool.py", line 339, in _async__init__
    await first_ch.connect()
  File "/Users/ajung/src/guillotina/lib/python3.6/site-packages/asyncpg/pool.py", line 123, in connect
    **self._connect_kwargs)
  File "/Users/ajung/src/guillotina/lib/python3.6/site-packages/asyncpg/connection.py", line 1378, in connect
    max_cacheable_statement_size=max_cacheable_statement_size)
  File "/Users/ajung/src/guillotina/lib/python3.6/site-packages/asyncpg/connect_utils.py", line 298, in _connect
    connection_class=connection_class)
  File "/Users/ajung/src/guillotina/lib/python3.6/site-packages/asyncpg/connect_utils.py", line 274, in _connect_addr
    await asyncio.wait_for(connected, loop=loop, timeout=timeout)
  File "/opt/buildout.python/parts/opt/lib/python3.6/asyncio/tasks.py", line 352, in wait_for
    return fut.result()
asyncpg.exceptions.InvalidAuthorizationSpecificationError: role "guillotina" does not exist
```

**Comment by vangheem** [comment]
Fixed with: https://github.com/plone/guillotina/issues/141

**Comment by zopyx** [comment]
How is this fixed?

**Comment by vangheem** [comment]
You're authenticating with a user that does not exist on the database.

I imagine this is because you were following the docs.

**Comment by zopyx** [comment]
The issues remains when I follow the new documentation from a fresh checkout. 

I assume that 

```
docker run -e POSTGRES_DB=guillotina -e POSTGRES_USER=guillotina -p 127.0.0.1:5432:5432 postgres:9.6
````

is not sufficient and a setup might be missing.

**Comment by vangheem** [comment]
Docs should match release 1.5.3 right now.

```
$ docker run -e POSTGRES_DB=guillotina -e POSTGRES_USER=guillotina -p 127.0.0.1:5432:5432 postgres:9.6
```

```
./bin/pip install guillotina
./bin/g
```

on fresh virtualenv is working for me

**Comment by zopyx** [comment]
hm....works on Linux, issue above encountered on Mac

**Comment by vangheem** [comment]
Weird, I'm also on mac.

FWIW, you can also create a `config.yaml` and try changing the connection settings instead of using the defaults:

```
---
databases:
- db:
    storage: postgresql
    dsn:
      scheme: postgres
      dbname: guillotina
      user: postgres
      host: localhost
      password: ''
      port: 5432
```

Maybe it's how docker is binding the port on the host for you?
